# Generated by Django 4.2.7 on 2023-11-08 11:58

import netfields.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                ("mac", netfields.fields.MACAddressField(unique=True)),
                ("ip", netfields.fields.InetAddressField(max_length=39, unique=True)),
            ],
        ),
    ]
