# Generated by Django 4.2.7 on 2023-11-17 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Route",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("source", models.TextField()),
                ("sink", models.TextField()),
            ],
            options={
                "unique_together": {("source", "sink")},
            },
        ),
    ]
