# Generated by Django 4.2.7 on 2024-02-18 21:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("device", "0002_route"),
    ]

    operations = [
        migrations.CreateModel(
            name="TWIModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(unique=True)),
                (
                    "address",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(127),
                            django.core.validators.MinValueValidator(1),
                        ]
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="device",
            name="twi_modules",
            field=models.ManyToManyField(blank=True, to="device.twimodule"),
        ),
    ]
